version: '3'
services:
  zyz-slidev:
    build: ./docker
    container_name: zyzslidev
    user: node
    volumes:
      - ./slidev:/slidev
      - slidev_volume:/slidev/node_modules
    ports:
      - 3030:3030
    networks:
      - slidev
volumes:
  slidev_volume:
networks:
  slidev:
    driver: bridge